In [92]:
import pandas as pd
import numpy as np

In [2]:
label_raw = pd.read_csv("memory_sample_failure_tag_round1_a_train.csv")
print(label_raw)

    serial_number     failure_time  tag  manufacturer  vendor
0     server_1789   2019/2/4 20:03    0             0       0
1    server_13003   2019/3/3 16:11    0             0       0
2    server_15764   2019/4/11 8:23    0             0       0
3    server_27567  2019/3/30 17:36    0             0       0
4    server_33559   2019/3/19 7:01    0             0       0
..            ...              ...  ...           ...     ...
831  server_57227   2019/2/7 16:48    0             3       2
832  server_15750   2019/4/9 16:16    1             3       2
833  server_31066   2019/1/3 19:10    1             3       2
834  server_51997   2019/4/3 11:30    1             3       2
835  server_43096  2019/2/22 20:01    2             3       2

[836 rows x 5 columns]


In [5]:
sever_id = label_raw["serial_number"]

In [6]:
# 使用str.replace替换'Server_'为空字符串  
cleaned_id = sever_id.str.replace('server_', '')  

In [7]:
# 转换为数组,再转化为整型数字
id2 = np.array(cleaned_id).astype(int)

In [8]:
id3 = id2[id2 <= 30502]

In [25]:
# 创建一个空数组，在id3的位置设成1
labels = np.zeros(30502)
labels[id3-1] = 1 # 第0个位置对应的server_1 依次类推

In [26]:
np.save("data_processed/labels.npy", labels)

In [27]:
labels = np.load("data_processed/labels.npy")

In [30]:
print(labels[15764])

0.0


In [38]:
data_mce = np.load("./data_processed/data_mce.npy")

In [39]:
print(data_mce.shape)

(30502, 32, 16)


In [40]:
print(data_mce[0,:,:])



[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.

In [41]:
labels = np.load("data_processed/labels.npy")

In [43]:
print(labels.shape)

(30502,)


In [ ]:
## 使用trouble_tickets标签

In [99]:
## 读取trouble_tickets
data_csv = pd.read_csv("./failure_prediction/data_raw/trouble_tickets.csv")
print(data_csv)

               sid  failure_type          failed_time
0     Server_10003             2  0001-07-17 11:11:07
1     Server_10034             3  0001-08-11 07:35:07
2     Server_10074             3  0001-08-11 07:37:47
3     Server_10108             2  0001-07-13 03:51:43
4     Server_10152             2  0001-06-14 10:23:07
...            ...           ...                  ...
3012   Server_9912             3  0001-07-01 13:08:24
3013   Server_9942             3  0001-08-14 11:03:11
3014   Server_9944             3  0001-05-29 23:21:03
3015    Server_997             3  0001-02-25 01:30:02
3016    Server_998             3  0001-05-08 15:30:25

[3017 rows x 3 columns]


In [101]:
Server_id = data_csv["sid"]
print(Server_id)

0       Server_10003
1       Server_10034
2       Server_10074
3       Server_10108
4       Server_10152
            ...     
3012     Server_9912
3013     Server_9942
3014     Server_9944
3015      Server_997
3016      Server_998
Name: sid, Length: 3017, dtype: object


In [102]:
cleaned_id = Server_id.str.replace('Server_', '')  
print(cleaned_id)

0       10003
1       10034
2       10074
3       10108
4       10152
        ...  
3012     9912
3013     9942
3014     9944
3015      997
3016      998
Name: sid, Length: 3017, dtype: object


In [103]:
id2 = np.array(cleaned_id).astype(int)

In [114]:
id2[2547]

31380

In [115]:
id3 = id2[id2<30502]
print(len(id3))

2139


In [72]:
# 创建一个空数组，在id3的位置设成1
labels = np.zeros(30502)
labels[id3-1] = 1 # 第0个位置对应的server_1 依次类推

In [73]:
print(len(labels))

30502


In [79]:
np.save("labels.npy", labels)

In [87]:
print(sum(labels))

2139.0


In [91]:
labels[10034]

0.0

In [96]:
lables = np.load("./failure_prediction/data_processed/labels.npy")

In [97]:
print(sum(lables))

2139.0
